import { PERMISSIONS } from './permission.constant';

export const PERMISSION_GROUPS = {
  // ===== ADMIN =====
  ADMIN: [
    // Users
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_LOCK,
    PERMISSIONS.USERS_UNLOCK,
    PERMISSIONS.USERS_RESET_PASSWORD,

    // Roles & Permissions
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.ROLES_CREATE,
    PERMISSIONS.ROLES_UPDATE,
    PERMISSIONS.ROLES_DELETE,
    PERMISSIONS.PERMISSIONS_VIEW,
    PERMISSIONS.PERMISSIONS_CREATE,
    PERMISSIONS.PERMISSIONS_UPDATE,
    PERMISSIONS.PERMISSIONS_DELETE,

    // Products, Categories
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.PRODUCTS_IMPORT,
    PERMISSIONS.PRODUCTS_EXPORT,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CATEGORIES_CREATE,
    PERMISSIONS.CATEGORIES_UPDATE,
    PERMISSIONS.CATEGORIES_DELETE,

    // Orders, Inventory
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_PROCESS,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_IMPORT,
    PERMISSIONS.INVENTORY_EXPORT,
    PERMISSIONS.INVENTORY_UPDATE,

    // Reports, System Logs
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SYSTEMLOGS_VIEW,
    PERMISSIONS.SYSTEMLOGS_DELETE,

    // Dashboard & Settings
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_ANALYZE,
    PERMISSIONS.PASSWORDPOLICY_VIEW,
    PERMISSIONS.PASSWORDPOLICY_UPDATE,
  ],

  // ===== SELLER =====
  SELLER: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_PROCESS,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_IMPORT,
    PERMISSIONS.INVENTORY_EXPORT,
    PERMISSIONS.REPORTS_VIEW,
  ],

  // ===== CUSTOMER =====
  CUSTOMER: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CART_VIEW,
    PERMISSIONS.CART_ADD,
    PERMISSIONS.CART_UPDATE,
    PERMISSIONS.CART_DELETE,
    PERMISSIONS.FAVORITES_VIEW,
    PERMISSIONS.FAVORITES_ADD,
    PERMISSIONS.FAVORITES_DELETE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
  ],
};
